engines:
  duplication:
    enabled: true
    config:
      languages:
      - python
  fixme:
    enabled: true
  pep8:
    enabled: true
    checks:
      E501:
        enabled: false
  radon:
    enabled: true
    config:
      python_version: 2

ratings:
   paths:
   - "**.py"

exclude_paths:
- "**/test/**"
- "**/setup.py"
- "**/resources/**"