sudo: required
language: python

services:
  - docker

before_script:
  - chmod u+x **/*.sh
  - scripts/setup.sh
  - cd commons && tox && cd ..

script:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    scripts/build_base_image.sh;
    fi
  - scripts/build_app_images.sh

after_success:
  - docker run --interactive --tty --rm --env CODECLIMATE_CODE="$PWD" --volume "$PWD":/code --volume /var/run/docker.sock:/var/run/docker.sock --volume /tmp/cc:/tmp/cc codeclimate/codeclimate analyze
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    scripts/push-base-image.sh;
    fi