sudo: required

language: python

services:
  - docker

before_install:
  - pip install tox
  - cd ./commons
  - chmod 755 ./deploy.sh && tox
  - rm -rf .tox && rm -rf audiopyle_commons.egg-info
  - cd ../coordinator
  - chmod 755 ./deploy.sh && tox
  - rm -rf .tox && rm -rf .audiopyle_coordinator.egg-info
  - cd ../xtracter
  - chmod 755 ./deploy.sh && tox
  - rm -rf .tox && rm -rf .audiopyle_xtracter.egg-info
  - cd ..

script:
  - docker build -t "$DOCKER_USERNAME"/audiopyle-commons ./commons
  - docker build -t "$DOCKER_USERNAME"/audiopyle-coordinator ./coordinator
  - docker build -t "$DOCKER_USERNAME"/audiopyle-xtracter ./xtracter

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    docker push "$DOCKER_USERNAME"/audiopyle-commons
    docker push "$DOCKER_USERNAME"/audiopyle-coordinator
    docker push "$DOCKER_USERNAME"/audiopyle-xtracter
    fi
