sudo: required
language: python
python:
    - "3.6"

services:
  - docker

before_script:
  - chmod u+x **/*.sh
  - scripts/setup.sh
  - cd commons && tox && cd ..

script:
  - scripts/build_base_image.sh
  - scripts/build_app_images.sh
  - scripts/build_test_image.sh
  - docker-compose -f scripts/docker-compose-ci.yml up --no-build --abort-on-container-exit --timeout 30 --exit-code-from testcases
  - docker run --interactive --tty --rm --env CODECLIMATE_CODE="$PWD" --volume "$PWD":/code --volume /var/run/docker.sock:/var/run/docker.sock --volume /tmp/cc:/tmp/cc codeclimate/codeclimate analyze

after_success:

  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    scripts/push-base-image.sh;
    fi
