sudo: true
language: python
cache: pip
python:
  - "3.6"

services:
  - docker

jobs:
  include:
    - stage: os_deps
      script:
      - chmod u+x **/*.sh
      - sudo apt-get install -y libav-tools
    - stage: config
      script: make config
    - stage: unit_test
      script: make test
    - stage: build
      script: make build
    - stage: base_docker
      script: make basedocker
    - stage: docker
      script: make docker
    - stage: integration-test
      script: make verify
    - stage: publish_images
      script: scripts/push_images.sh $DOCKER_USERNAME $DOCKER_PASSWORD

stages:
  - os_deps
  - config
  - unit_test
  - build
  - base_docker
  - docker
  - integration_test
  - name: publish_images
    if: branch = master

notifications:
  email:
    on_success: never
    on_failure: change