sudo: required
language: python
python:
    - "3.6"

services:
  - docker

before_script:
  - chmod u+x **/*.sh
  - pip install tox numpy vamp

script:
  - scripts/run_unit_tests.sh
  - scripts/build_base_image.sh
  - scripts/build_app_images.sh
  - scripts/build_test_image.sh
  - scripts/run_integration_tests.sh
  - scripts/run_static_analysis.sh

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    scripts/push-base-image.sh;
    fi
