sudo: required
language: python
cache: pip
python:
    - "3.6"

services:
  - docker

before_script:
  - chmod u+x **/*.sh
  - scripts/install_os_build_deps.sh
  - scripts/install_py_build_deps.sh

script:
  - scripts/run_type_check.sh
  - scripts/run_unit_tests.sh
  - scripts/build_base_image.sh
  - scripts/build_app_images.sh
  - scripts/build_test_image.sh
  - scripts/run_integration_tests.sh

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    scripts/push-base-image.sh;
    fi

notifications:
  email:
    on_success: never
    on_failure: change