sudo: required

language: python

services:
  - docker

before_script:
  - chmod u+x setup.sh && ./setup.sh
  - cd ./commons && tox && cd ..

script:
  - docker build -t "$DOCKER_USERNAME"/audiopyle-commons ./commons
  - docker build -t "$DOCKER_USERNAME"/audiopyle-extractor ./api
  - docker build -t "$DOCKER_USERNAME"/audiopyle-coordinator ./api
  - docker run --interactive --tty --rm --env CODECLIMATE_CODE="$PWD" --volume "$PWD":/code --volume /var/run/docker.sock:/var/run/docker.sock --volume /tmp/cc:/tmp/cc codeclimate/codeclimate analyze
