version: '3'

services:
  rabbitmq:
    image: "rabbitmq:3.6-alpine"
    hostname: "rabbitmq"
    environment:
      RABBITMQ_ERLANG_COOKIE: "YCNMKDZOOPNXITXYRWMP"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
  mysql:
    image: mysql:5.7
    hostname: "mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=audiopyle
      - MYSQL_PASSWORD=audiopyle
      - MYSQL_DATABASE=audiopyle
    ports:
      - "3306:3306"
  coordinator:
    image: "endlessdrones/audiopyle-coordinator:latest"
    hostname: "coordinator"
    ports:
      - "8080:8080"
    volumes:
      - "./resources/vamp:/root/vamp:ro"
      - "./resources/audio:/root/audio:ro"
    environment:
      - BLACKLISTED_PLUGINS=qm-dwt:qm-vamp-plugins:wcoeff,silvet:silvet:templates,melodiaviz:mtg-melodia:contoursall,melodiaviz:mtg-melodia:saliencefunction,melodiaviz:mtg-melodia:contoursmelody,qm-adaptivespectrogram:qm-vamp-plugins:output,pyin:pyin:candidatesalience,yin:pyin:salience,dct:vamp-libxtract:dct,amdf:vamp-libxtract:amdf,asdf:vamp-libxtract:asdf,autocorrelation:vamp-libxtract:autocorrelation,powerspectrum:vamp-example-plugins:powerspectrum,silvet:silvet:timefreq,cqvampmidi:cqvamp:constantq,bbc-rhythm:bbc-vamp-plugins:autocor,spectrum:vamp-libxtract:amplitudes,pyin:pyin:f0candidates,pyin:pyin:f0probs,bbc-rhythm:bbc-vamp-plugins:average,bbc-rhythm:bbc-vamp-plugins:onset_curve,bbc-rhythm:bbc-vamp-plugins:diff,cqchromavamp:cqvamp:chromagram,harmonic_spectrum:vamp-libxtract:amplitudes,peak_spectrum:vamp-libxtract:amplitudes
      - RABBITMQ_SERIVCE_HOST=rabbitmq
      - MYSQL_SERVICE_HOST=mysql
      - MYSQL_SERVICE_PORT=3306
    depends_on:
      - rabbitmq
  extractor_1:
    image: "endlessdrones/audiopyle-extractor:latest"
    hostname: "extractor_1"
    volumes:
      - "./resources/vamp:/root/vamp:ro"
      - "./resources/audio:/root/audio:ro"
    environment:
      - EXTRACTION_CONCURRENCY=4
      - EXTRACTION_BROKER_CONN_POOL_SIZE=4
      - EXTRACTION_SOFT_TIME_LIMIT_SECONDS=300
      - EXTRACTION_HARD_TIME_LIMIT_SECONDS=600
      - EXTRACTION_MEMORY_LIMIT_MB=512
      - RABBITMQ_SERIVCE_HOST=rabbitmq
      - MYSQL_SERVICE_HOST=mysql
      - MYSQL_SERVICE_PORT=3306
    depends_on:
      - rabbitmq
      - mysql