rabbit1:
  image: "rabbitmq:3.6-alpine"
  hostname: "rabbit1"
  environment:
    RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
    RABBITMQ_DEFAULT_USER: "rabbitmq"
    RABBITMQ_DEFAULT_PASS: "rabbitmq"
    RABBITMQ_DEFAULT_VHOST: "/"
redis1:
    image: redis:3.0-alpine
    hostname: "redis1"
redisCommander:
  image: tenstartups/redis-commander
  hostname: "redisCommander"
  command: --redis-host redis1
  links:
    - redis1
  ports:
    - "8081:8081"
coordinator1:
  image: "endlessdrones/audiopyle-coordinator"
  hostname: "coordinator1"
  links:
    - rabbit1
    - redis1
  ports:
    - "8080:8080"
  volumes:
    - "/home/mkorzeni/vamp:/root/vamp"
    - "/home/mkorzeni/projects/audiopyle/resources:/audio"
analyzer1:
  image: "endlessdrones/audiopyle-analyzer"
  hostname: "analyzer1"
  links:
    - rabbit1
    - redis1
  volumes:
    - "/home/mkorzeni/vamp:/root/vamp"
    - "/home/mkorzeni/projects/audiopyle/resources:/audio"
