rabbitmq_host:
  image: "rabbitmq:3.6-alpine"
  hostname: "rabbitmq_host"
  environment:
    RABBITMQ_ERLANG_COOKIE: "YCNMKDZOOPNXITXYRWMP"
    RABBITMQ_DEFAULT_USER: "rabbitmq"
    RABBITMQ_DEFAULT_PASS: "rabbitmq"
    RABBITMQ_DEFAULT_VHOST: "/"
mysql_host:
  image: mysql:5.7
  hostname: "mysql_host"
  environment:
    - MYSQL_ROOT_PASSWORD=secret
    - MYSQL_USER=celery
    - MYSQL_PASSWORD=celery
    - MYSQL_DATABASE=results
  ports:
    - "3305:3306"
coordinator_host:
  image: "endlessdrones/audiopyle-coordinator"
  hostname: "coordinator_host"
  links:
    - rabbitmq_host
    - mysql_host
  ports:
    - "8080:8080"
  volumes:
    - "./resources/vamp:/root/vamp"
    - "./resources/audio:/audio"
    - "./resources/results:/results"
  environment:
    - BLACKLISTED_PLUGINS=vamp-example-plugins:zerocrossing,vamp-example-plugins:powerspectrum
extractor_host_1:
  image: "endlessdrones/audiopyle-extractor"
  hostname: "extractor_host_1"
  links:
    - rabbitmq_host
    - mysql_host
  volumes:
    - "./resources/vamp:/root/vamp"
    - "./resources/audio:/audio"
    - "./resources/results:/results"
  environment:
    - EXTRACTION_CONCURRENCY=2
    - EXTRACTION_BROKER_CONN_POOL_SIZE=4
    - EXTRACTION_SOFT_TIME_LIMIT_SECONDS=300
    - EXTRACTION_HARD_TIME_LIMIT_SECONDS=600
    - EXTRACTION_MEMORY_LIMIT_MB=128