version: '3'

services:
  rabbitmq:
    image: "rabbitmq:3.6-alpine"
    hostname: "rabbitmq"
    environment:
      RABBITMQ_ERLANG_COOKIE: "YCNMKDZOOPNXITXYRWMP"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
  mysql:
    image: mysql:5.7
    hostname: "mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=audiopyle
      - MYSQL_PASSWORD=audiopyle
      - MYSQL_DATABASE=audiopyle
    ports:
      - "3306:3306"
  coordinator:
    image: "endlessdrones/audiopyle-coordinator:latest"
    hostname: "coordinator"
    ports:
      - "8080:8080"
    volumes:
      - "./resources/vamp:/root/vamp:ro"
      - "./resources/audio:/root/audio:ro"
    environment:
      - BLACKLISTED_PLUGINS=qm-vamp-plugins:qm-dwt:wcoeff,mtg-melodia:melodiaviz:saliencefunction,mtg-melodia:melodiaviz:contoursmelody,mtg-melodia:melodiaviz:contoursall,qm-vamp-plugins:qm-adaptivespectrogram:output,pyin:yin:salience,vamp-libxtract:autocorrelation:autocorrelation,vamp-libxtract:asdf:asdf,vamp-libxtract:dct:dct,vamp-libxtract:amdf:amdf,vamp-example-plugins:powerspectrum:powerspectrum,cqvamp:cqvampmidi:constantq,bbc-vamp-plugins:bbc-rhythm:autocor,vamp-libxtract:spectrum:amplitudes
      - RABBITMQ_SERIVCE_HOST=rabbitmq
      - MYSQL_SERVICE_HOST=mysql
      - MYSQL_SERVICE_PORT=3306
    depends_on:
      - rabbitmq
  extractor_1:
    image: "endlessdrones/audiopyle-extractor:latest"
    hostname: "extractor_1"
    volumes:
      - "./resources/vamp:/root/vamp:ro"
      - "./resources/audio:/root/audio:ro"
    environment:
      - EXTRACTION_CONCURRENCY=4
      - EXTRACTION_BROKER_CONN_POOL_SIZE=4
      - EXTRACTION_SOFT_TIME_LIMIT_SECONDS=300
      - EXTRACTION_HARD_TIME_LIMIT_SECONDS=600
      - EXTRACTION_MEMORY_LIMIT_MB=512
      - RABBITMQ_SERIVCE_HOST=rabbitmq
      - MYSQL_SERVICE_HOST=mysql
      - MYSQL_SERVICE_PORT=3306
    depends_on:
      - rabbitmq
      - mysql