version: '3'

networks:
  default:

services:
  rabbitmq:
    networks:
      default:
        aliases:
          - rabbitmq.local
    image: "rabbitmq:3.6-alpine"
    hostname: "rabbitmq"
    environment:
      RABBITMQ_ERLANG_COOKIE: "YCNMKDZOOPNXITXYRWMP"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
  mysql:
    networks:
      default:
        aliases:
          - mysql.local
    image: mysql:5.7
    hostname: "mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=audiopyle
      - MYSQL_PASSWORD=audiopyle
      - MYSQL_DATABASE=audiopyle
    ports:
      - "3306:3306"
    volumes:
      - "./resources/config/mysql:/etc/mysql/conf.d"
  coordinator:
    networks:
      default:
        aliases:
          - coordinator.local
    image: "endlessdrones/audiopyle-coordinator:latest"
    hostname: "coordinator"
    ports:
      - "8080:8080"
    volumes:
      - "./resources/config:/root/config:ro"
      - "./resources/vamp:/root/vamp:ro"
      - "./resources/audio:/root/audio:ro"
    environment:
      - RABBITMQ_SERIVCE_HOST=rabbitmq.local
      - MYSQL_SERVICE_HOST=mysql.local
      - MYSQL_SERVICE_PORT=3306
    depends_on:
      - rabbitmq
  extractor_1:
    networks:
      default:
        aliases:
          - extractor_1.local
    image: "endlessdrones/audiopyle-extractor:latest"
    hostname: "extractor_1"
    volumes:
      - "./resources/vamp:/root/vamp:ro"
      - "./resources/audio:/root/audio:ro"
    environment:
      - EXTRACTION_CONCURRENCY=4
      - EXTRACTION_BROKER_CONN_POOL_SIZE=4
      - EXTRACTION_SOFT_TIME_LIMIT_SECONDS=240
      - EXTRACTION_HARD_TIME_LIMIT_SECONDS=300
      - EXTRACTION_MEMORY_LIMIT_MB=1024
      - RABBITMQ_SERIVCE_HOST=rabbitmq.local
      - MYSQL_SERVICE_HOST=mysql.local
      - MYSQL_SERVICE_PORT=3306
    depends_on:
      - rabbitmq
      - mysql