---
swagger: "2.0"
info:
  description: An API offering inputs and outputs from the Audiopyle app
  title: Audiopyle API
  version: 0.0.1
definitions:
  FileDetail:
    type: object
    properties:
      file_name:
        type: string
      size:
        description: "File size in bytes"
        type: integer
      created_on:
        description: "Unix creation date (UTC) in ISO 8601 format"
        type: string
        format: date-time
      last_modification:
        description: "Unix last modification date (UTC) in ISO 8601 format"
        type: string
        format: date-time
      last_access:
        description: "Unix last access date (UTC) in ISO 8601 format"
        type: string
        format: date-time
    required:
    - file_name
    - size
    - created_on
    - last_modification
    - last_access
  AudioTag:
    type: object
    properties:
      artist:
        type: string
      album:
        type: string
      title:
        type: string
      genre:
        type: string
      track:
        description: "Track number on an album"
        type: integer
      date:
        description: "Year of album release"
        type: integer
    required:
    - artist
    - album
    - title
    - genre
    - track
    - date
  MetricConfig:
    type: object
    additionalProperties:
      type: object
      properties:
        plugin:
          type: string
        transformation:
          type: object
          properties:
            name:
              type: string
            kwargs:
              type: object
              additionalProperties: true
      required:
      - plugin
      - transformation
  PluginConfig:
    type: object
    additionalProperties:
      type: object
      properties:
        block_size:
          type: integer
          nullable: true
        step_size:
          type: integer
          nullable: true
      additionalProperties: true
  ExtractionRequest:
    type: object
    properties:
      uuid:
        type: string
        nullable: true
      audio_file_name:
        type: string
      plugin_full_key:
        type: string
      plugin_config:
        type: object
        nullable: true
      metric_config:
        type: object
        nullable: true
    required:
    - audio_file_name
    - plugin_full_key
  VampPlugin:
    type: object
    properties:
      vendor:
        type: string
      name:
        type: string
      output:
        type: string
      library_file_name:
        type: string
      required:
      - vendor
      - name
      - output
      - library_file_name
paths:
  "/audio/":
    get:
      description: Returns list of available audio file names
      responses:
        200:
          description: A list of file names
          schema:
            type: array
            items:
              type: string
          examples: [
            "102bpm_drum_loop.flac",
            "102bpm_drum_loop.mp3"
          ]
  "/audio/{file_name}":
    get:
      description: Returns list of available audio file names
      parameters:
      - in: path
        name: file_name
        required: true
        type: string
      responses:
        200:
          description: "Details of given audio file"
          schema:
            "$ref": "#/definitions/FileDetail"
          examples: {
            created_on: "2018-08-16 08:58:49",
            file_name: "102bpm_drum_loop.flac",
            last_access: "2018-08-16 08:58:49",
            last_modification: "2018-08-16 08:58:49",
            size: 111690
          }
        400:
          description: "file_name parameter was not provided in URL"
        404:
          description: "Can not find a file with given name"
  "/audio/{file_name}/tag":
    get:
      description: Returns given audio file tag
      parameters:
      - in: path
        name: file_name
        required: true
        type: string
      responses:
        200:
          description: Id3 tag of given audio file
          schema:
            "$ref": "#/definitions/AudioTag"
          examples: {
            album: "Unknown Album",
            artist: "Unknown Artist",
            date: 2017,
            genre: "Unknown Genre",
            title: "Unknown Title",
            track: 1
          }
        204:
          description: Given audio file does not have Id3 tags
        400:
          description: file_name parameter was not provided in URL
        404:
          description: Can not find a file with given name
  "/plugin":
    get:
      description: Returns list of available VAMP plugins
      responses:
        200:
          description: List of available VAMP plugins
          schema:
            type: array
            items:
              type: string
          examples: [
            "vamp-example-plugins:amplitudefollower:amplitude",
            "vamp-example-plugins:percussiononsets:onsets"
          ]
  "/plugin/{vendor}/{name}/{output}":
    get:
      description: Returns details of given VAMP plugin
      parameters:
      - name: vendor
        in: path
        required: true
        type: string
      - name: name
        in: path
        required: true
        type: string
      - name: output
        in: path
        required: true
        type: string
      responses:
        200:
          description: Details of given VAMP plugin
          schema:
            "$ref": "#/definitions/VampPlugin"
        400:
          description: Vendor, name or output parameter were not given
        404:
          description: Plugin with given vendor, name or output dos not exist
  "/config/metric":
    get:
      description: Returns available metric configuration
      responses:
        200:
          description: Content of metric config JSON file
          schema:
            "$ref": "#/definitions/MetricConfig"
        404:
          description: There was no metric config file found
  "/config/plugin":
    get:
      description: Returns available plugin configuration
      responses:
        200:
          description: Content of plugin config JSON file
          schema:
            "$ref": "#/definitions/PluginConfig"
          examples: {
            "vamp-example-plugins:amplitudefollower:amplitude": {
              "block_size":4096,
              "step_size":4096
            }
          }
        404:
          description: There was no plugin config file found