---
swagger: "2.0"
info:
  description: An API offering inputs and outputs from the Audiopyle app
  title: Audiopyle API
  version: 0.0.1
definitions:
  FileDetail:
    type: object
    properties:
      file_name:
        type: string
      size:
        description: "File size in bytes"
        type: integer
      created_on:
        description: "Unix creation date (UTC) in format: %Y-%m-%d %H:%M:%S"
        type: string
      last_modification:
        description: "Unix last modification date (UTC) in format: %Y-%m-%d %H:%M:%S"
        type: string
      last_access:
        description: "Unix last access date (UTC) in format: %Y-%m-%d %H:%M:%S"
        type: string
  AudioTag:
    type: object
    properties:
      artist:
        type: string
      album:
        type: string
      title:
        type: string
      genre:
        type: string
      track:
        description: "Track number on an album"
        type: integer
      date:
        description: "Year of album release"
        type: integer
  MetricConfig:
    type: object
    additionalProperties:
      type: object
      properties:
        plugin:
          type: string
        transformation:
          type: object
          properties:
            name:
              type: string
            kwargs:
              type: object
              additionalProperties: true
  PluginConfig:
    type: object
    additionalProperties:
      type: object
      properties:
        block_size:
          type: integer
          nullable: true
        step_size:
          type: integer
          nullable: true
      additionalProperties: true
  ExtractionRequest:
    type: object
    properties:
      uuid:
        type: string
      audio_file_name:
        type: string
      plugin_full_key:
        type: string
      plugin_config:
        type: object
        nullable: true
      metric_config:
        type: object
        nullable: true
paths:
  "/audio/":
    get:
      description: Returns list of available audio file names
      responses:
        200:
          description: A list of file names
          schema:
            type: array
            items:
              type: string
  "/audio/{file_name}":
    get:
      description: Returns list of available audio file names
      parameters:
      - in: path
        name: file_name
        required: true
        type: string
      responses:
        200:
          description: "Details of given audio file"
          schema:
            "$ref": "#/definitions/FileDetail"
          examples:
            application/json: {
                  created_on: "2018-08-16 08:58:49",
                  file_name: "102bpm_drum_loop.flac",
                  last_access: "2018-08-16 08:58:49",
                  last_modification: "2018-08-16 08:58:49",
                  size: 111690
              }
        400:
          description: "file_name parameter was not provided in URL"
        404:
          description: "Can not find a file with given name"
  "/audio/{file_name}/tag":
    get:
      description: Returns given audio file tag
      parameters:
      - in: path
        name: file_name
        required: true
        type: string
      responses:
        200:
          description: Id3 tag of given audio file
          schema:
            "$ref": "#/definitions/AudioTag"
          examples:
            application/json: {
                  album: "Unknown Album",
                  artist: "Unknown Artist",
                  date: 2017,
                  genre: "Unknown Genre",
                  title: "Unknown Title",
                  track: 1
              }
        204:
          description: Given audio file does not have Id3 tags
        400:
          description: file_name parameter was not provided in URL
        404:
          description: Can not find a file with given name
  "/request/automation":
    post:
      description: Creates Cartesian product of requests from list of audio files and available (non-blacklisted) VAMP plugins and sends them for execution
      responses:
        202:
          description: Returns details of generated requests
          schema:
            type: array
            items:
              "$ref": "#/definitions/ExtractionRequest"
          examples:
            application/json: [
                  {
                      "audio_file_name": "102bpm_drum_loop.flac",
                      "metric_config": null,
                      "plugin_config": null,
                      "plugin_full_key": "vamp-example-plugins:spectralcentroid:logcentroid",
                      "uuid": "0b04c1b3-b366-5145-9248-6cb118d3be99"
                  }
              ]
        412:
          description: Audio files directory or VAMP plugins directory is empty; could not generate requests
  "/config/metric":
    get:
      description: Returns available metric configuration
      responses:
        200:
          description: Content of metric config JSON file
          schema:
            "$ref": "#/definitions/MetricConfig"
        404:
          description: There was no metric config file found
  "/config/plugin":
    get:
      description: Returns available plugin configuration
      responses:
        200:
          description: Content of plugin config JSON file
          schema:
            "$ref": "#/definitions/PluginConfig"
        404:
          description: There was no plugin config file found