version: '3'

networks:
  default:

services:
  rabbitmq:
    networks:
      default:
        aliases:
          - rabbitmq.local
    image: "rabbitmq:3.6-alpine"
    hostname: "rabbitmq"
    environment:
      RABBITMQ_ERLANG_COOKIE: "YCNMKDZOOPNXITXYRWMP"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
  mysql:
    networks:
      default:
        aliases:
          - mysql.local
    image: mysql:5.7
    hostname: "mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=audiopyle
      - MYSQL_PASSWORD=audiopyle
      - MYSQL_DATABASE=audiopyle
    ports:
      - "3306:3306"
    volumes:
      - "./resources/config/mysql:/etc/mysql/conf.d:ro"
  api:
    networks:
      default:
        aliases:
          - api.local
    image: "emkor/audiopyle-api:latest"
    hostname: "api"
    ports:
      - "8080:8080"
    volumes:
      - "./resources/config:/root/config:ro"
      - "./resources/vamp:/root/vamp:ro"
      - "./resources/audio:/root/audio:ro"
    environment:
      - RABBITMQ_SERIVCE_HOST=rabbitmq.local
      - MYSQL_SERVICE_HOST=mysql.local
      - MYSQL_SERVICE_PORT=3306
    depends_on:
      - rabbitmq
  worker:
    networks:
      default:
        aliases:
          - worker.local
    image: "emkor/audiopyle-worker:latest"
    hostname: "worker"
    volumes:
      - "./resources/vamp:/root/vamp:ro"
      - "./resources/audio:/root/audio:ro"
    environment:
      - EXTRACTION_FULL_RESULT_PERSISTENCE=1
      - EXTRACTION_NORMALIZE_AUDIO_VOLUME_TO_DBFS=-20
      - EXTRACTION_CONCURRENCY=4
      - EXTRACTION_BROKER_CONN_POOL_SIZE=4
      - EXTRACTION_SOFT_TIME_LIMIT_SECONDS=240
      - EXTRACTION_HARD_TIME_LIMIT_SECONDS=300
      - EXTRACTION_MEMORY_LIMIT_MB=1024
      - RABBITMQ_SERIVCE_HOST=rabbitmq.local
      - MYSQL_SERVICE_HOST=mysql.local
      - MYSQL_SERVICE_PORT=3306
    depends_on:
      - rabbitmq
      - mysql

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.3.0
    volumes:
    - ./resources/elk/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
    - "9200:9200"
    - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
    - default

  logstash:
    image: docker.elastic.co/logstash/logstash-oss:6.3.0
    volumes:
    - ./resources/elk/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
    - ./resources/elk/logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
    - "5000:5000"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
    - default
    depends_on:
    - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.3.0
    volumes:
    - ./resources/elk/kibana/config/:/usr/share/kibana/config:ro
    ports:
    - "5601:5601"
    networks:
    - default
    depends_on:
    - elasticsearch
