rabbitmq_host:
  image: "rabbitmq:3.6-alpine"
  hostname: "rabbitmq_host"
  environment:
    RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
    RABBITMQ_DEFAULT_USER: "rabbitmq"
    RABBITMQ_DEFAULT_PASS: "rabbitmq"
    RABBITMQ_DEFAULT_VHOST: "/"
mysql_host:
  image: mysql:5.7
  hostname: "mysql_host"
  environment:
    - MYSQL_ROOT_PASSWORD=secret
    - MYSQL_USER=celery
    - MYSQL_PASSWORD=celery
    - MYSQL_DATABASE=results
  ports:
    - "3305:3306"
coordinator_host:
  image: "endlessdrones/audiopyle-coordinator"
  hostname: "coordinator_host"
  links:
    - rabbitmq_host
    - mysql_host
  ports:
    - "8080:8080"
  volumes:
    - "./resources/vamp:/root/vamp"
    - "./resources/audio:/audio"
extractor_host_1:
  image: "endlessdrones/audiopyle-extractor"
  hostname: "extractor_host_1"
  links:
    - rabbitmq_host
    - mysql_host
  volumes:
    - "./resources/vamp:/root/vamp"
    - "./resources/audio:/audio"
testcases:
  image: "endlessdrones/audiopyle-testcases"
  hostname: "testcases"
  environment:
    AUDIOPYLE_BOOT_TIME: "10"
    CI_BUILD: "1"
  links:
    - coordinator_host
    - extractor_host_1
