version: '3'

services:
  rabbitmq:
    networks:
      default:
        aliases:
          - rabbitmq.local
    image: "rabbitmq:3.6-alpine"
    hostname: "rabbitmq"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
  mysql:
    networks:
      default:
        aliases:
          - mysql.local
    image: mysql:5.7
    hostname: "mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=audiopyle
      - MYSQL_PASSWORD=audiopyle
      - MYSQL_DATABASE=audiopyle
    volumes:
      - "./resources/config/mysql:/etc/mysql/conf.d:ro"
  api:
    networks:
      default:
        aliases:
          - api.local
    image: "emkor/audiopyle-api:latest"
    hostname: "api"
    ports:
      - "8080:8080"
    volumes:
      - "./resources/config:/root/config:ro"
      - "./resources/vamp:/root/vamp:ro"
      - "./resources/audio:/root/audio:ro"
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_SERIVCE_HOST=rabbitmq.local
      - MYSQL_SERVICE_HOST=mysql.local
      - MYSQL_SERVICE_PORT=3306
  worker_1:
    networks:
      default:
        aliases:
          - worker_1.local
    image: "emkor/audiopyle-worker:latest"
    hostname: "worker_1"
    volumes:
      - "./resources/vamp:/root/vamp:ro"
      - "./resources/audio:/root/audio:ro"
    depends_on:
      - rabbitmq
      - mysql
    environment:
      - RABBITMQ_SERIVCE_HOST=rabbitmq.local
      - MYSQL_SERVICE_HOST=mysql.local
      - MYSQL_SERVICE_PORT=3306
      - EXTRACTION_CONCURRENCY=1
      - EXTRACTION_BROKER_CONN_POOL_SIZE=1
      - EXTRACTION_SOFT_TIME_LIMIT_SECONDS=30
      - EXTRACTION_HARD_TIME_LIMIT_SECONDS=60
      - EXTRACTION_MEMORY_LIMIT_MB=128
  testcases:
    networks:
      default:
        aliases:
          - testcases.local
    image: "emkor/audiopyle-testcases:latest"
    hostname: "testcases"
    environment:
      - COORDINATOR_SERVICE_HOST=api.local
      - COORDINATOR_SERVICE_PORT=8080